#!/usr/bin/env python3
"""Map Unity objects that contain known Mighty DOOM endpoints without exporting assets.

The script reads the sanitized report generated by analyze_apk.py, extracts only
Addressables bundles that already contain a known official hostname into a
private temporary directory, asks patch_unity_bundle.inspect_bundle() for
object-level metadata, and writes a sanitized JSON map. Temporary bundle bytes
are deleted automatically.
"""
from __future__ import annotations

import argparse
import json
import tempfile
import zipfile
from pathlib import Path
from typing import Any

from patch_unity_bundle import UnityPyUnavailable, inspect_bundle


def candidate_bundle_paths(report: dict[str, Any]) -> list[str]:
    paths: list[str] = []
    seen: set[str] = set()
    for hit in report.get("host_hits", []):
        if not isinstance(hit, dict):
            continue
        name = hit.get("file")
        if not isinstance(name, str):
            continue
        if not name.startswith("assets/aa/") or not name.endswith(".bundle"):
            continue
        if name not in seen:
            seen.add(name)
            paths.append(name)
    return paths


def sanitize_inspection(bundle_path: str, inspection: dict[str, Any]) -> dict[str, Any]:
    return {
        "bundle": bundle_path,
        "serializable": inspection.get("serializable", []),
        "raw_only": inspection.get("raw_only", []),
        "serializable_references": int(inspection.get("serializable_references", 0)),
        "raw_only_references": int(inspection.get("raw_only_references", 0)),
    }


def inspect_apk(apk: Path, report: dict[str, Any]) -> dict[str, Any]:
    requested = candidate_bundle_paths(report)
    results: list[dict[str, Any]] = []

    with zipfile.ZipFile(apk, "r") as zf, tempfile.TemporaryDirectory(prefix="mighty-doom-unity-") as tmp:
        root = Path(tmp)
        members = set(zf.namelist())
        for index, member in enumerate(requested):
            if member not in members:
                results.append({"bundle": member, "error": "missing-from-apk"})
                continue

            # Never use the proprietary member path as an on-disk directory
            # tree. A generated filename also avoids accidental persistence.
            temp_bundle = root / f"candidate-{index:04d}.bundle"
            with zf.open(member, "r") as src, temp_bundle.open("wb") as dst:
                while True:
                    chunk = src.read(1024 * 1024)
                    if not chunk:
                        break
                    dst.write(chunk)

            try:
                inspection = inspect_bundle(temp_bundle)
                results.append(sanitize_inspection(member, inspection))
            except Exception as exc:
                results.append({"bundle": member, "error": type(exc).__name__})
            finally:
                temp_bundle.unlink(missing_ok=True)

    serializable = sum(int(x.get("serializable_references", 0)) for x in results)
    raw_only = sum(int(x.get("raw_only_references", 0)) for x in results)
    return {
        "candidate_bundles": len(requested),
        "inspected_bundles": len(results),
        "serializable_references": serializable,
        "raw_only_references": raw_only,
        "bundles": results,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("apk")
    parser.add_argument("--report", required=True, help="JSON sanitizado criado por analyze_apk.py")
    parser.add_argument("--json-out", required=True)
    args = parser.parse_args()

    apk = Path(args.apk).expanduser().resolve()
    report_path = Path(args.report).expanduser().resolve()
    out = Path(args.json_out).expanduser().resolve()
    if not apk.is_file() or not report_path.is_file():
        print("ERRO: APK ou relatório sanitizado não encontrado.")
        return 2

    try:
        report = json.loads(report_path.read_text(encoding="utf-8"))
        result = inspect_apk(apk, report)
    except UnityPyUnavailable as exc:
        print(str(exc))
        return 5
    except (json.JSONDecodeError, zipfile.BadZipFile) as exc:
        print(f"ERRO: entrada inválida: {exc}")
        return 2

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
